spring.application.name=EventManagementSystemAdvanced
server.address=0.0.0.0
server.port=8080


#Database Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/EventManagement
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Rishabh@28
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

##mongoDb
#spring.data.mongodb.uri=mongodb://localhost:27017/EventManagamentSystem

#Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jaatboykumar12@gmail.com
spring.mail.password=vfzh evcl nhcq cmqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

#jwt
jwt.expiration=86400000
jwt.secretKey=klsjdfhgheruighjkfhdgihuirhgkjadvihfuibviudfbvuiefvjibdifgkjadfKSJDFKJHFBSDJKVBUISJSBVIHASUIHIUEARGKV


#Razor pay
razorpay.api.key=rzp_test_RajIeawiamBuBm
razorpay.api.secret=GkLHB96YIZnAa6oSewbI64hp



#cloudinary configurantion
cloudinary.cloud_name=dbalm9rfj
cloudinary.api_key=139943314983217
cloudinary.api_secret_key=DxZx9dDdx3u_zH0Tc68CvkFUmLk


spring.jpa.open-in-view=false

# --- File upload limits ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB





