spring.application.name=EventManagementSystemAdvanced
server.address=0.0.0.0
server.port=8080


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis


# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

# JWT
jwt.secretKey=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

# Razorpay
razorpay.api.key=${RAZORPAY_KEY}
razorpay.api.secret=${RAZORPAY_SECRET}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret_key=${CLOUDINARY_SECRET}

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.file.name=logs/event-system.log
logging.level.root=INFO
logging.level.org.rishabh.eventmanagementsystemadvanced=DEBUG
logging.level.org.springframework=ERROR
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB


# Elasticsearch is running locally
spring.data.elasticsearch.repositories.enabled=true

# If Elasticsearch security is disabled (you didn?t enable xpack)
spring.elasticsearch.uris=http://localhost:9200

spring.devtools.restart.enabled=false


